<?php 
	$title = 'Update Baby Care Duration';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
	echo $this->formLabel($form->get('employeeNumber'));
	echo $this->formElement($form->get('employeeNumber'));
	echo $this->formElementErrors($form->get('employeeNumber'));
	echo $this->formLabel($form->get('startingDate'));
	echo $this->formElement($form->get('startingDate'));
	echo $this->formElementErrors($form->get('startingDate'));
	echo $this->formLabel($form->get('endingDate'));
	echo $this->formElement($form->get('endingDate'));
	echo $this->formElementErrors($form->get('endingDate')); 	
	echo $this->formLabel($form->get('startingTime'));
	echo $this->formElement($form->get('startingTime'));
	echo $this->formElementErrors($form->get('startingTime'));
	echo $this->formLabel($form->get('endingTime'));
	echo $this->formElement($form->get('endingTime'));
	echo $this->formElementErrors($form->get('endingTime')); 
	echo $this->formSubmit($form->get('submit'));
	echo $this->form ()->closeTag ();
?>
