<h1>Edit Bank</h1>


<?php
echo $this->form ()->openTag ( $form );
echo $this->formRow ( $form->get ( 'lkp_bank_id' ) );
echo $this->formRow ( $form->get ( 'bank_name' ) ) . "</br>";
echo $this->formRow ( $form->get ( 'branch' ) ) . "</br>";
echo $this->formRow ( $form->get ( 'account_number' ) ) . "</br>";
echo $this->formSubmit ( $form->get ( 'submit' ) );
echo $this->form ()->closeTag ();
?>
</br>
</br>
<a href="<?php echo $this->url('bank'); ?>">Back</a>
