<?php 
	$title = 'Close Final Entitlement'; 
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form); 
	echo $this->formLabel($form->get('employeeNumberFinalEntitlement'));
	echo $this->formElement($form->get('employeeNumberFinalEntitlement'));
	echo $this->formElementErrors($form->get('employeeNumberFinalEntitlement'));
	echo "<br/><br/>";
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>  
<br/>
<br/> 