<html>
<head>
<?php
echo $this->headScript()
          ->prependFile($this->basePath() . '/js/sorttable.js');
?>
<!-- <script type="text/javascript" src="/js/sorttable.js"></script>-->

<script type="text/javascript">
/*var newTableObject = document.getElementById('paysheetTable'); 
alert(newTableObject); 
	sorttable.makeSortable(newTableObject);
/*$(document).ready(function() { 
    //alert("");
	$("#myTable").tablesorter(); 
});*/  
</script>
<style>
/*table.sortable th:not(.sorttable_sorted):
not(.sorttable_sorted_reverse):not(.sorttable_nosort):after { 
    content: " \25B4\25BE" 
}*/
table.sortable thead {
    background-color:#eee;
    color:#666666;
    font-weight: bold;
    cursor: default;
}
table, td, th { border: 1px solid #ccc;border-collapse: collapse; }
thead { background-color: #ccc;color:#000;font-weight:bold; }
th { background-color: '#ccc';color: #000; }
td { padding: 5px; }
td { height: 40px;vertical-align: bottom;border-collapse: collapse; }
</style>
</head>
<body>
<?php 
$title = 'Report Paysheet';
$this->headTitle($title); 
 
echo $this->reportHelper($this->name,$this->allowance,
		$this->deduction,$this->companyDeduction,$this->report); 
?> 

</body>
</html> 