<style type="text/css"> 
    label  { font-weight:normal; }
    li { color:red; }
</style> 
<div id="tabs">
	<ul> 
		<li><a href="#tabs-1">Traveling Form Local (Admin Approval)</a></li>
		<!-- <li><a href="#tabs-2">Search Leave</a></li>--> 
	</ul>  
<div id="tabs-1"> 
<?php echo $this->form()->openTag($form);  ?>
<div>
    <fieldset style="padding:5px;" >
        <legend>Traveling Form(Local) Info</legend>
            <div style="float:left;width:900px;margin:-10px 0 0 0;">
                <?php echo $travelInfo; ?> 
            </div> 		
    </fieldset> 
    <fieldset style="padding:5px;" >
        <legend></legend>
            <div style="float:left;width:320px;margin:-10px 0 0 0;">
            <?php 
                //echo $this->formLabel($form->get('id'));
                echo $this->formElement($form->get('id'));
                echo $this->formElementErrors($form->get('id'));
                echo $this->formLabel($form->get('expenseApproved'));
                echo $this->formElement($form->get('expenseApproved'));
                echo $this->formElementErrors($form->get('expenseApproved'));
                echo $this->formLabel($form->get('approvalType'));
                echo $this->formElement($form->get('approvalType'));
                echo $this->formElementErrors($form->get('approvalType')); 
            ?> 
            </div>				
            <div style="Float:left;width:320px;"></div>	
            <div style="Float:left;width:320px;"></div>			
    </fieldset> 
    <fieldset style="padding:5px;" >
        <legend></legend>
            <div style="float:left;width:320px;margin:-10px 0 0 0;">
            <?php
                echo $this->formSubmit($form->get('submit'));
            ?>
            </div> 
    </fieldset> 
</div>
<?php echo $this->form()->closeTag ();?>
</div>
<!-- <div id="tabs-2">
<p>search form</p>
</div>--> 
</div>