<?php 
	$title = 'Update Bank';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
	echo $this->formLabel($form->get('bankName'));
	echo $this->formElement($form->get('bankName'));
	echo $this->formElementErrors($form->get('bankName'));
	echo $this->formLabel($form->get('branch'));
	echo $this->formElement($form->get('branch'));
	echo $this->formElementErrors($form->get('branch'));
	echo $this->formLabel($form->get('accountNumber'));
	echo $this->formElement($form->get('accountNumber'));
	echo $this->formElementErrors($form->get('accountNumber')); 
	echo $this->formSubmit($form->get('submit'));
	echo $this->form ()->closeTag ();
?>
