<?php 
	$title = 'Update Anniversay Increment';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
	
	echo $this->formLabel($form->get('employeeId'));
    echo $this->formElement($form->get('employeeId'));
    echo $this->formElementErrors($form->get('employeeId'));
    echo $this->formLabel($form->get('oldAmount'));
	echo $this->formElement($form->get('oldAmount'));
	echo $this->formElementErrors($form->get('oldAmount'));
	echo $this->formLabel($form->get('newAmount'));
	echo $this->formElement($form->get('newAmount'));
	echo $this->formElementErrors($form->get('newAmount'));
	
	echo $this->formSubmit($form->get('submit'));
	echo $this->form ()->closeTag ();
?>
