<?php 
	$title = 'Update Location';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
	echo $this->formLabel($form->get('locationName'));
	echo $this->formElement($form->get('locationName'));
	echo $this->formElementErrors($form->get('locationName'));
	echo $this->formLabel($form->get('overtimeHour'));
	echo $this->formElement($form->get('overtimeHour'));
	echo $this->formElementErrors($form->get('overtimeHour'));
	echo $this->formLabel($form->get('isHaveHardship'));
	echo $this->formElement($form->get('isHaveHardship'));
	echo $this->formElementErrors($form->get('isHaveHardship'));
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form ()->closeTag ();
?>
