<?php
namespace Allowance\Model;

use Allowance\Model\Cola;
//require_once 'C:\Program Files (x86)\Zend\Apache2\htdocs\hrmNew\module\Allowance\src\Cola.php';

/**
 * Test class for Cola.
 * Generated by PHPUnit on 2014-11-06 at 10:54:28.
 */
class ColaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cola
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Cola('10');
    }
    
    /**
     * @covers Allowance\Model\Cola::getAmount
     * @todo Implement testGetAmount().
     */
    public function testGetAmount()
    {
        // Remove the following lines when you implement this test.
        $stack = array();
        $this->assertEquals(0, count($stack));

        array_push($stack, 'foo');
        $this->assertEquals('foo', $stack[count($stack)-1]);
        $this->assertEquals(1, count($stack));

        $this->assertEquals('foo', array_pop($stack));
        $this->assertEquals(0, count($stack));
    }

    /**
     * @covers Allowance\Model\Cola::setAmount
     * @todo Implement testSetAmount().
     */
    public function testSetAmount()
    {
        // Remove the following lines when you implement this test.
        $stack = array();
        $this->assertEquals(0, count($stack));

        array_push($stack, 'foo');
        $this->assertEquals('foo', $stack[count($stack)-1]);
        $this->assertEquals(1, count($stack));

        $this->assertEquals('foo', array_pop($stack));
        $this->assertEquals(0, count($stack));
    }
}
?>
