<?php 
	$title = 'Add Overtime';  
	$this->headTitle($title);  
	//echo "<h3>".$title."</h3>";  
?> 
<style type="text/css">
    label  { font-weight:normal; }
    li { color:red; }
    #subToSupDialog { display:none; } 
    td { font-size: 20px;}
</style>
<div > 
<table cellspacing="10px" cellpadding="10px">
  <col width="105" />
  <col width="64" span="5" />
  <col width="85" />
  <col width="64" />
  <tr> 
    <td width="105">employee name</td>
    <td width="64">Ahmed</td>
    <td width="64"></td>
    <td width="64"></td>
    <td width="64"></td>
    <td width="64"></td>
    <td width="85"></td>
    <td width="64"></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Date</td>
    <td>in time</td>
    <td>out time</td>
    <td>tot hrs</td>
    <td>ot hrs</td>
    <td>late hrs</td>
    <td>holiday hrs</td>
    <td>meal</td>
  </tr>
  <tr>
    <td>6 sep 2017</td>
    <td>8:00AM</td>
    <td>5:00PM</td>
    <td align="right">9</td>
    <td align="right">1</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>7 sep 2017</td>
    <td>8:00AM</td>
    <td>5:30PM</td>
    <td align="right">9.5</td>
    <td align="right">1</td>
    <td align="right">0.5</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>8 sep 2017</td>
    <td>10:00AM</td>
    <td>12:00PM</td>
    <td align="right">2</td>
    <td></td>
    <td></td>
    <td align="right">2</td>
    <td>1</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td>tot</td>
    <td align="right">20.5</td>
    <td align="right">2</td>
    <td align="right">0.5</td>
    <td align="right">2</td>
    <td>1</td>
  </tr>
</table>
</div> 