<?php /*
<?xml version="1.0" encoding="UTF-8"?>
<DataSet> 
	<xs:schema id="NewDataSet">
		<xs:element name="NewDataSet" msdata:IsDataSet="true"
			msdata:UseCurrentLocale="true">
			<xs:complexType>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="Table">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="FIRST_NAMES" type="xs:string"
									minOccurs="0" />
								<xs:element name="LAST_NAME" type="xs:string"
									minOccurs="0" />
								<xs:element name="NAME" type="xs:string" minOccurs="0" />
								<xs:element name="FATHER_NAME" type="xs:string"
									minOccurs="0" />
								<xs:element name="GRAND_FATHER_NAME" type="xs:string"
									minOccurs="0" />
								<xs:element name="GRE_GRA_FATHER_NAME" type="xs:string"
									minOccurs="0" />
								<xs:element name="FATHER_OLD_CERTIFICATE_NO" type="xs:string"
									minOccurs="0" />
								<xs:element name="MOTHER_NAME" type="xs:string"
									minOccurs="0" />
								<xs:element name="FATHER_IDENTITY_NUMBER" type="xs:string"
									minOccurs="0" />
								<xs:element name="PROFESSION_ARABIC" type="xs:string"
									minOccurs="0" />
								<xs:element name="IDENTITY_NUMBER" type="xs:string"
									minOccurs="0" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:complexType>
		</xs:element>
	</xs:schema>
	<diffgr:diffgram>
		<NewDataSet>
			<Table diffgr:id="Table1" msdata:rowOrder="0">
				<FIRST_NAMES>mohamed awad mohamed</FIRST_NAMES>
				<LAST_NAME>saleem</LAST_NAME>
				<NAME>κ₯κ§</NAME>
				<FATHER_NAME>??ΰ</FATHER_NAME>
				<GRAND_FATHER_NAME>κ₯κ§</GRAND_FATHER_NAME>
				<GRE_GRA_FATHER_NAME>«ιοκ</GRE_GRA_FATHER_NAME>
				<MOTHER_NAME>λ€κο?</MOTHER_NAME>
				<PROFESSION_ARABIC>¬©?ο</PROFESSION_ARABIC>
				<IDENTITY_NUMBER>10100233782</IDENTITY_NUMBER>
			</Table>
		</NewDataSet>
	</diffgr:diffgram>
</DataSet>
*/
?> 