<?php 
	$title = 'Close Repayment';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form); 
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>  
<br/>
<div id="dialog">Are you sure remove this record?</div>
<div id="advanceRepaymentContainer"></div>
<script>$("#advanceRepaymentContainer").zfTable('/repaymentadvance/ajaxlist');</script> 
<br/> 