<script>

</script>
<?php
$title = 'Add Alerts';
$this->headTitle($title);
echo "<h3>".$title."</h3>";
?>

<?php 
    //$form->setAttribute('action', $this->url('/', array('action' => 'add')));
    $form->prepare();
	echo $this->form()->openTag($form);
	
	//echo $this->formLabel($form->get('id'));
	//echo $this->formElement($form->get('id'));
	
	echo $this->formLabel($form->get('alertId'));
	echo $this->formElement($form->get('alertId'));
		
	echo $this->formLabel($form->get('positionId'));
	echo $this->formElement($form->get('positionId'));
	
	echo $this->formLabel($form->get('formula'));
	echo $this->formElement($form->get('formula'));
	
	echo $this->formLabel($form->get('isCC'));
	echo $this->formElement($form->get('isCC'));
	
	echo '</div> ';
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>