<?php 
$title = 'Report Employee'; 
$this->headTitle($title); 
?>
<style>
table, td, th { border: 1px solid #ccc;border-collapse: collapse; }
thead { background-color: #ccc;color:#000;font-weight:bold; }
th { background-color: green;color: white; }
td { padding: 5px; }
td { height: 40px;vertical-align: bottom;border-collapse: collapse; }
</style>
<div id="tabs">
<table> 
<?php 
foreach ($manual as $m) { 
    echo "<tr><td><b><h3>".$m['title']."</h3></b></td></tr>";
    echo "<tr><td>".$m['content']."</td></tr>";
}
?> 
</table>
</div>  