<?php 
$title = 'Assessment List';
$this->headTitle($title);
?>
<!--  <div id="tableContainer"></div>
<script>$("#tableContainer").zfTable('/peoplemanagement/ajaxlist');</script>-->
<h2>Select Nominee</h2>
<table width="100%" border="1" cellpadding="5px">
  <tbody>
    <tr>
      <td><strong>Nominee List</strong></td>
    </tr>
    <tr>
      <td><a href="http://hrold/lbvf/assessnominee/assess/empId/14/jgId/16/partId/0">Ahmed Taha Ahmed Karar</a></td>
    </tr>
  </tbody>
</table>  
<br></br><br></br> 
<table width="100%" border="1" cellpadding="5px">
  <tbody>
    <tr>
      <td><strong>Partially Assessed List</strong></td>
    </tr>
    <tr>
      <td><a href="http://hrold/lbvf/assessnominee/assess/empId/14/jgId/16/partId/0">Ahmed Taha Ahmed Karar</a></td>
    </tr>
  </tbody>
</table>  