<?php 
	$title = 'Apply Employee Rating'; 
	$this->headTitle($title); 
	echo "<h3>".$title."</h3>"; 
?>

<?php 
	echo $this->form()->openTag($form);  
	echo $this->formSubmit($form->get('submit'));  
	echo $this->form()->closeTag();   
?>  
<br/> 
<div id="dialog">Are you sure remove this record?</div>
<div id="employeeRatingContainer"></div>
<script>$("#employeeRatingContainer").zfTable('/employeerating/ajaxlist');</script>  
<br/>