<?php 
	$title = 'Add Car Rent Group';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formLabel($form->get('groupName'));
	echo $this->formElement($form->get('groupName'));
	echo $this->formElementErrors($form->get('groupName'));
	echo $this->formLabel($form->get('amount'));
	echo $this->formElement($form->get('amount'));
	echo $this->formElementErrors($form->get('amount'));
	echo $this->formLabel($form->get('Notes'));
	echo $this->formElement($form->get('Notes'));
	echo $this->formElementErrors($form->get('Notes')); 
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>