<?php 
	$title = 'Apply New Initial Salary'; 
	$this->headTitle($title); 
	echo "<h3>".$title."</h3>"; 
?>
<?php 
	echo $this->form()->openTag($form);  
	echo $this->formLabel($form->get('applyeEfectiveDate'));
    echo $this->formElement($form->get('applyeEfectiveDate'));
    echo $this->formElementErrors($form->get('applyeEfectiveDate'));
	echo $this->formSubmit($form->get('submit'));  
	echo $this->form()->closeTag();   
?>  
<br/> 
<div id="dialog">Are you sure remove this record?</div>
<div id="employeeInitialContainer"></div>
<script>$("#employeeInitialContainer").zfTable('/employeeinitial/ajaxlist');</script> 
<br/>