<?php 
	$title = 'Close Advance Housing';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form); 
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>  
<br/>
<div id="dialog">Are you sure remove this record?</div>
<div id="advanceHousingContainer"></div>
<script>$("#advanceHousingContainer").zfTable('/advancehousing/ajaxlist');</script> 
<br/>