
<table  border='1' class='sortable' font-size='6px' align='center' id='table1' width='100%' bordercolorlight='#C0C0C0' bordercolordark='#C0C0C0' style='border-collapse: collapse'>
	<thead >
	<tr>
		<th bgcolor='#F0F0F0'>#</th>
		<th bgcolor='#F0F0F0'>Employee name</th>
		<th bgcolor='#F0F0F0'>Net Due</th>
		<th bgcolor='#F0F0F0'>Account No</th>		
	</tr>	
	</thead>
    <tbody class='scrollingContent'>
    <tr >
        <td><p align='center'>&nbsp;1</td>
		<td><p align='left'>&nbsp;Hayder Osman Ahmed Mohamed</td>
		<td><p align='right'>&nbsp;29125.8</td>
		<td><p align='right'>&nbsp;1330279</td>
	</tr> 
	</tbody>
	<tfoot>
	    <tr>
            <td><p align='center'>&nbsp;</td>            
		    <td><p align='left'><b>Total</b></td>
		    <td><p align='right'>&nbsp;90358.78</td>
		    <td><p align='center'>&nbsp;</td>
	    </tr>	
	</tfoot>		
</table>