<?php 
	$title = 'Close Leave Allowance'; 
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form); 

	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>  
<br/>
<div id="dialog">Are you sure remove this record?</div> 
<div id="tableContainer"></div>
<script>$("#tableContainer").zfTable('/leaveallowance/ajaxlist');</script> 
<br/><br/>