<?php 
	$title = 'Select Leave Allowance Employee'; 
	$this->headTitle($title); 
	//echo "<h3>".$title."</h3>"; 
    echo $this->form()->openTag($form);	
?>
<div style="width:100%;>
<div id="my" style="width:750px;float:left;clear:both;">
<fieldset style="padding:5px;" >
<legend>Add Employee for leave allowance</legend>
<div style="float:left;width:370px;margin:-10px 0 0 0;">
<?php 
echo $this->formLabel($form->get('employeeNumberLeaveAllowance'));
echo $this->formElement($form->get('employeeNumberLeaveAllowance'));
echo $this->formElementErrors($form->get('employeeNumberLeaveAllowance')); 
echo $this->formSubmit($form->get('submit'));
?> 
 </div>	
 <div style="Float:left;width:370px;">
 <?php
echo $this->form()->closeTag(); 
?> 
</div>	
</fieldset>				
</div>  
<br/> 
<div id="dialog">Are you sure remove this record?</div> 
<div id="tableContainer"></div>
<script>$("#tableContainer").zfTable('/leaveallowance/ajaxlist');</script> 
<br/><br/>
</div>