<?php 
	$title = 'Apply Employee Termination';  
	$this->headTitle($title); 
	echo "<h3>".$title."</h3>";  
?>

<?php 
	echo $this->form()->openTag($form);  
	echo $this->formSubmit($form->get('submit'));  
	echo $this->form()->closeTag();   
?>  
<br/> 
<div id="dialog">Are you sure remove this record?</div>
<div id="tableContainerT"></div>
<script>$("#tableContainerT").zfTable('/employeetermination/ajaxlist');</script>
<br/>