<?php 
	$title = 'Open/Close Year(Closes the current year and opens new year)';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>
<br/>
<br/> 
<?php 
	echo $this->form()->openTag($form); 
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>  
<?php 
/* 
<br/>
<div id="dialog">Are you sure remove this record?</div>
<div id="advanceHousingContainer"></div>
<script>$("#advanceHousingContainer").zfTable('/advancehousing/ajaxlist');</script> 
<br/>
*/ 
?>