<?php 
	$title = 'Close Payment Difference/Arrears';  
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>
 
<?php 
	echo $this->form()->openTag($form); 
	echo $this->formLabel($form->get('diffShortDescription'));
	echo $this->formElement($form->get('diffShortDescription'));
	echo $this->formElementErrors($form->get('diffShortDescription')); 
	echo $this->formSubmit($form->get('submit'));   
	echo $this->form()->closeTag();  
?>  
<br/> 
<br/> 