<?php echo $this->doctype(); ?>
<html lang="en">
<head>


</head>
<body style="background-color: #FFFFFF;">

	<div class="container">
            <?php echo $this->content; ?>
            
        </div>
	<!-- /container -->

	<hr>
	<footer>
		<p>&copy; 2017 ICT OECL. <?php echo $this->translate('All rights reserved.') ?></p>
	</footer>
        <?php echo $this->inlineScript()?>
    </body>
</html>
