<?php 
	$title = 'Add Advance Salary'; 
	$this->headTitle($title); 
	//echo "<h3>".$title."</h3>"; 
?>
<div >
<?php 

$form = $this->form; 
/* $form->setAttribute('action', $this->url(
	'paysheet', array(
		'action'     => 'viewreport',
		'controller' => 'paysheet'
	)
)); */ 
$form->setAttribute('target','_blank'); 
$form->prepare(); 
    
?>
</div> 
<style type="text/css">
    label  { font-weight:normal; }
    li { color:red; }
</style>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Advance Salary</a></li>
		<!-- <li><a href="#tabs-2">Search Report</a></li>-->
	</ul> 
<div id="tabs-1"> 
<?php echo $this->form()->openTag($form); ?>
<div> 
    <fieldset style="padding:5px;" >
        <legend>Add/Edit Advance Salary</legend>
            <div style="float:left;width:320px;margin:-10px 0 0 0;">
            <?php 
                echo $this->formLabel($form->get('employeeNumberAdvSalary'));
                echo $this->formElement($form->get('employeeNumberAdvSalary'));
                echo $this->formElementErrors($form->get('employeeNumberAdvSalary'));
                echo $this->formLabel($form->get('advancePaidDate'));
				echo $this->formElement($form->get('advancePaidDate'));
				echo $this->formElementErrors($form->get('advancePaidDate'));
				echo $this->formLabel($form->get('numberOfMonthsDue'));
				echo $this->formElement($form->get('numberOfMonthsDue'));
				echo $this->formElementErrors($form->get('numberOfMonthsDue'));
				echo $this->formSubmit($form->get('submit')); 
				?>
				 </div>	
                <div style="Float:left;width:370px;">
             <?php 
				echo $this->formLabel($form->get('netPay'));
				echo $this->formElement($form->get('netPay'));
				echo $this->formElementErrors($form->get('netPay'));
				echo $this->formLabel($form->get('numberOfMonthsNetPay'));
				echo $this->formElement($form->get('numberOfMonthsNetPay'));
				echo $this->formElementErrors($form->get('numberOfMonthsNetPay'));
				echo $this->formLabel($form->get('monthlyDue'));
				echo $this->formElement($form->get('monthlyDue'));
				echo $this->formElementErrors($form->get('monthlyDue')); 
				echo $this->formLabel($form->get('advanceAmount'));
				echo $this->formElement($form->get('advanceAmount'));
				echo $this->formElementErrors($form->get('advanceAmount'));
            ?>
                
            </div>				
            	</div>	
    </fieldset>
    <!--
    <fieldset style="padding:5px;" >
        <legend>Submit Form</legend>
            <div style="float:left;width:320px;margin:-10px 0 0 0;">
            <?php
                //echo $this->formSubmit($form->get('submit'));
            ?>
            </div>
    </fieldset>
    --> 
</div> 
<?php echo $this->form()->closeTag();?>
</div>
<div id="dialog">Are you sure remove this record?</div> 
<div id="advanceSalaryContainer"></div>
<script>$("#advanceSalaryContainer").zfTable('/advancesalary/ajaxlist');</script> 

<br/><br/>
<!-- 
    <div id="tabs-2">
        <p>search form</p>
    </div>
-->
</div> 