<?php 
	$title = 'Update Employee Type';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
    echo $this->formLabel($form->get('employeeTypeName'));
	echo $this->formElement($form->get('employeeTypeName'));
	echo $this->formElementErrors($form->get('employeeTypeName'));  
	echo $this->formSubmit($form->get('submit'));
	echo $this->form ()->closeTag ();
?>
