<?php
$title = 'Add New Department';
$this->headTitle ( $title );
echo "<h3>create new department </h3>";

$addForm->setAttribute ( 'action', $this->url ( 'department', array (
		'action' => 'add' 
) ) );
echo $this->form ()->openTag ( $addForm );
echo $this->formHidden ( $addForm->get ( 'id' ) );
echo "<label>ID</label>" . $this->formRow ( $addForm->get ( 'department_id' ) ) . "<br/>";
echo "<label>Code</label>" . $this->formRow ( $addForm->get ( 'dept_function_code' ) ) . "<br/>";
echo "<label>Name</label>" . $this->formRow ( $addForm->get ( 'department_name' ) ) . "<br/>";
echo "<label>no_of_work_days</label>" . $this->formRow ( $addForm->get ( 'no_of_work_days' ) ) . "<br/>";
echo "<label>dept_assistant_position</label>" . $this->formSelect ( $addForm->get ( 'dept_assistant_position_id' ) ) . "<br/>";
echo "<label>work_hours_per_day</label>" . $this->formRow ( $addForm->get ( 'work_hours_per_day' ) ) . "<br/>";
echo "<label></label>" . $this->formSubmit ( $addForm->get ( 'submit' ) );
echo $this->form ()->closeTag ();

echo $result;