<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Index
 *
 * @author AlkhatimVip
 */
$title = 'Main Departments';
$this->headTitle ( $title );
?>
<table class="table">
	<thead>
		<th>Function Code</th>
		<th>Name</th>
		<th>noOfWorkDays</th>
		<th>deptAssistantPosition</th>
		<th>workHoursPerDay</th>
		<th>&nbsp;</th>
	</thead>
        <?php foreach ($departments as $department) : ?>
            <tr>
		<td><?php echo $this->escapeHtml($department->getDeptFunctionCode());?></td>
		<td><?php echo $this->escapeHtml($department->getDepartmentName());?></td>
		<td><?php echo $this->escapeHtml($department->getNoOfWorkDays());?></td>
		<td><?php echo $this->escapeHtml($department->getDeptAssistantPositionId());?></td>
		<td><?php echo $this->escapeHtml($department->getWorkHoursPerDay());?></td>
		<td><a
			href="<?php echo $this->url('department',array('action' => 'edit','id'=> $department->getDepartmentId()));?>">edit</a></td>
	</tr> 
        <?php endforeach; ?>
    </table>