<?php echo $this->doctype(); ?> 
<html lang="en"> 
<head>  
<meta charset="utf-8"> 
        <?php 
            echo $this->headTitle('Test' . $this->translate('HRM'))
                      ->setSeparator(' - ')
                      ->setAutoEscape(false); ?>  
        <?php  
			echo $this->headMeta()
			          ->appendName('viewport', 'width=device-width, initial-scale=1.0')
			          ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); 
			
			echo $this->headLink(array(
					    'rel' => 'shortcut icon',
					    'type' => 'image/vnd.microsoft.icon',
					    'href' => $this->basePath() . '/img/PetronasNewlogo.png'))
					  ->prependStylesheet($this->basePath() . '/css/style.css')
					  ->prependStylesheet($this->basePath() . '/css/jquery-combobox.css')
			          ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.css')
			          ->prependStylesheet($this->basePath() . '/css/bootstrap-3.0.0/bootstrap.min.css')
			          ->prependStylesheet($this->basePath() . '/css/hr.css')
			          ->prependStylesheet($this->basePath() . '/css/jquery.timepicker.min.css')
			          ->prependStylesheet($this->basePath() . '/fonts/font-awesome-4.7.0/css/font-awesome.min.css')
			          ->prependStylesheet($this->basePath() . '/css/richtext.min.css') 
			; 
            
			echo $this->headScript()
			          ->prependFile($this->basePath() . '/js/jquery.validate.js')
			          ->prependFile($this->basePath() . '/js/jquery.ui.combobox.js')
			          ->prependFile($this->basePath() . '/js/jquery-ui-1.10.js')
			          ->prependFile($this->basePath() . '/js/jquery-2.1.1.js')
			          ->appendFile($this->basePath() . '/js/jquery.timepicker.min.js')
			          ->appendFile($this->basePath() . '/js/hr.js')
			          //->appendFile($this->basePath() . '/js/hr.js')
			          ->appendFile($this->basePath() . '/js/jquery.richtext.js')
			          ->appendFile($this->basePath() . '/js/common.js')
			          ->appendFile($this->basePath() . '/js/validationForms.js')
			          ->appendFile($this->basePath() . '/js/zf-table.js')
			;  
            
		?> 
	<link rel="stylesheet" href="/js/jquery.treeview.css" />
	<script src="/js/jquery.cookie.js" type="text/javascript"></script>
	<script src="/js/jquery.treeview.min.js" type="text/javascript"></script>
	<link type="text/css" href="/css/menu.css" rel="stylesheet" />
	
	<style type="text/css">
		html, body {
			margin: 0;
			padding: 0;
			
		}
		body ,#content{
		    background: #fff url(../img/new_logo_01.jpg) repeat-x  top left;
		}
		.noselect {
			  -webkit-touch-callout: none; /* iOS Safari */
			    -webkit-user-select: none; /* Safari */
			     -khtml-user-select: none; /* Konqueror HTML */
			       -moz-user-select: none; /* Firefox */
			        -ms-user-select: none; /* Internet Explorer/Edge */
			            user-select: none; /* Non-prefixed version, currently
			                                  supported by Chrome and Opera */
			}
	</style>
	<style type="text/css" media="print">
        BODY {display:none;visibility:hidden;}
     </style>
</head>

<body >
    <div id="container"> 
	    <div id="wrapper">
		    <div id="content">
			    <div>
					<!-- <br style="clear: both;">--> 
					<div class="noselect">
						<?php 
							$flash = $this->flashMessenger(); 					
							echo $flash->render('error', array('errorMsg'));
							echo $flash->render('info', array('noticeMsg'));
							echo $flash->render('default', array('noticeMsg'));
							echo $flash->render('success', array('successMsg'));
						?>
                        <?= $this->layout()->content; ?>
                    </div>
                    <hr><br /><br /> 
				    <footer>
						<p>&copy; 2017 ICT OECL. All rights reserved</p>
				    </footer> 
				</div>
			</div>
		</div> 
        
		<div id="navigation" style="">
			<div>
				<p style="font-size: 16px;" align="center">
				<?php 
				     if ($user = $this->identity()) {
				         echo '<b>'.$user['username'].' | <a href="/logout">Logout</a></b> ';
				     } else {
				         echo 'Not logged in';
				     }  
				 ?> 
				</p> 
				<div>
				<?php echo $this->navigation()->menu('navigation'); ?>
					
				</div>
			</div>
		</div> 
		</div> 
</body>

</html>