<?php 
	$title = 'Apply Special Loan';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>  
<?php 
	echo $this->form()->openTag($form); 
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>  
<br/>
<div id="dialog">Are you sure remove this record?</div>
<div id="specialLoanContainer"></div>
<script>$("#specialLoanContainer").zfTable('/specialloan/ajaxlist');</script> 
<br/>