<?php 
	$title = 'Update Special Loan Due';
	$this->headTitle($title);
	//echo "<h3>".$title."</h3>";
?>
<div >
<?php 

//$form = $this->form; 
/* $form->setAttribute('action', $this->url(
	'paysheet', array(
		'action'     => 'viewreport',
		'controller' => 'paysheet'
	)
)); */  
//$form->setAttribute('target','_blank'); 
//$form->prepare(); 
    
?>
</div> 
<style type="text/css">
    label  { font-weight:normal; }
    li { color:red; }
</style>


<div id="dialog">Are you sure remove this record?</div> 
<div id="specialLoanContainer"></div>
<script>$("#specialLoanContainer").zfTable('/specialloan/updatedueajaxlist');</script> 
<br/><br/><br/>
<div id="specialLoanContainerPaid"></div>
<script>$("#specialLoanContainerPaid").zfTable('/specialloan/updatedueajaxlist');</script> 
<!--  
    <div id="tabs-2">
        <p>search form</p>
    </div>
-->
</div> 