<?php
namespace Allowance\Model;


require_once 'C:\Program Files (x86)\Zend\Apache2\htdocs\hrmNew\module\Allowance\src\Initial.php';

/**
 * Test class for Initial.
 * Generated by PHPUnit on 2014-11-06 at 11:40:24.
 */
class InitialTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Initial
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Initial;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Allowance\Model\Initial::getAmount
     * @todo Implement testGetAmount().
     */
    public function testGetAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Allowance\Model\Initial::setAmount
     * @todo Implement testSetAmount().
     */
    public function testSetAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
