<h3>Add Assessor </h3> 
<div id="lbvf"> <br />
  <p><strong> Read the following Instruction and add Assessee Participation details as per the sample format given;</strong></p>
  <p>People  Management/Staff Involvement captures executive&rsquo;s   contribution through  participation in various initiatives by the   company.   These initiatives  facilitate the executives to exercise their   leadership competencies and shared  values.   It provides evidences especially in the Leadership Dimension-Develops    People to facilitate assessor in providing objective feedback   on the  executive&rsquo;s leadership behaviour and shared values.</p>
  <p><strong><em><u>Note</u></em></strong><strong><em>:</em></strong>Below are the examples of People  Management/Staff Involvement   for Categories, Roles, and Level of Involvement.    The examples are for assessee&rsquo;s reference before filling in their People  Management/Staff Involvement   in the table provided.</p>
  <table border-collapse="collapse" bordercolor="#CCCCCC" border="1" cellspacing="0" cellpadding="5px">
    <tbody>
      <tr>
        <td width="385"><p align="center"><strong>Example of Types of    Category</strong></p></td>
        <td width="150"><p align="center"><strong>Role</strong></p></td>
        <td width="198"><p align="center"><strong>Level of Involvement</strong></p></td>
      </tr>
      <tr>
        <td width="385"><p>Organising events (i.e Teambuilding, Family Day,    Engagement, etc)</p></td>
        <td rowspan="9" width="150"><p align="center">Leader<br />
          Team Member<br />
          Trainer<br />
          Chairman<br />
          Facilitator<br />
          Speaker<br />
          Assessor<br />
          Panel<br />
          Coach<br />
          Participant <br />
          Focal Person<br />
          Administrator<br />
          Content    Manager/Coordinator<br />
          Moderator<br />
          Change Agent<br />
          Subject Matter Expert<br />
          Other</p></td>
        <td rowspan="9" width="198"><p align="center">Unit/Division/Department<br />
          OPU/HCU<br />
          PETRONAS<br />
          National<br />
          International<br />
          Networking Group<br />
          Other</p></td>
      </tr>
      <tr>
        <td width="385"><p>Involvement in Young Professional Club (YPC),    PETRONITA, KKP, etc</p></td>
      </tr>
      <tr>
        <td width="385"><p>Focus Group Discussions/Workshop </p></td>
      </tr>
      <tr>
        <td width="385"><p>Triple Plus initiatives</p></td>
      </tr>
      <tr>
        <td width="385"><p>Cross functional or cross-business initiatives (i.e    Business Improvement Process – BIP)</p></td>
      </tr>
      <tr>
        <td width="385"><p>Organising CSR or community relations activities    (i.e Program Bakti Pendidikan PETRONAS - PBPP, Sentuhan Kasih, etc)</p></td>
      </tr>
      <tr>
        <td width="385"><p>Others (i.e: task force, event management, etc) <br />
          -Please    specify in the remarks column</p></td>
      </tr>
      <tr>
        <td width="385"><p>Knowledge Management</p></td>
      </tr>
      <tr>
        <td width="385"><p>No involvement at all</p></td>
      </tr>
    </tbody>
  </table>
  <u><br clear="all" />
  </u>
  <p><u>Instructions</u>: </p>
  <p>Please state People  Management/Staff Involvement in the table   provided below (to be filled by  assessee only). Please note that each   category can be selected up to a maximum  of three (3) times except for   &lsquo;Others&rsquo;. (*)  requires a compulsory field. </p>
  <p>However, should there  is no category stated in the table above suits   with assessee&rsquo;s involvement,  please choose &lsquo;Others&rsquo; and state on what   has been involved, efforts done, and  results achieved in the &lsquo;Remarks&rsquo;   Column.</p>
  <p><u>The People  Management/Staff Involvement will be in the assessors&rsquo;   feedback form and as reference  before they can provide their feedback   on the assessee in the LBVF  questionnaires.</u></p>
  <p> </p>
  <table border="1" cellspacing="0" cellpadding="5px">
    <tbody>
      <tr>
        <td width="149"><p><strong>Types of Category</strong></p></td>
        <td width="103"><p><strong>Role</strong></p></td>
        <td width="162"><p><strong>Level of    Involvement</strong></p></td>
        <td width="96"><p><strong>Frequency/Duration    (*)</strong></p></td>
        <td width="192"><p><strong>Remarks (*)</strong></p></td>
      </tr>
      <tr>
        <td width="149" valign="top"><p>e.g.; Organizing    Events (i.e Teambuilding, Family Day, Engagement, etc)</p></td>
        <td width="103" valign="top"><p>Team Member</p></td>
        <td width="162" valign="top"><p>Unit/Division/<br />
          Department</p></td>
        <td width="96" valign="top"><p>Involve in the    preparation for 3 months</p></td>
        <td width="192" valign="top"><p>Be a team member    for Family Day   for the LCD Department. The preparation took place for 3    months and   was in charges for the Logistics.</p></td>
      </tr>
      <tr>
        <td width="149" valign="top"><p>e.g.; Others (i.e:    task force, event management, etc) <br />
          - Please specify in the remarks column</p></td>
        <td width="103" valign="top"><p>Team Member</p></td>
        <td width="162" valign="top"><p>OPU/HCU</p></td>
        <td width="96" valign="top"><p>2 Months</p></td>
        <td width="192" valign="top"><p>Involved in a    Taskforce team for   CPDD initiative. Be a team member and be part of the    planning and   strategy for how to implement the new strategy for PETRONAS.</p></td>
      </tr>
    </tbody>
  </table>
</div>
<br/><br/> 
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">People Management/Staff Involvement</a></li>
		<!--  <li><a href="#tabs-2">Search Form</a></li>--> 
	</ul>
<div id="tabs-1"> 
<?php
echo $this->form ()->openTag ( $form );
?>
<div style="width:100%;>
<div  id="my"
	style="width:750px;float:left;clear:both;">
	<fieldset style="padding: 5px;">
		<!-- <legend>Add Form</legend>--> 
		<div style="float: left; width: 370px; margin: -10px 0 0 0;">
<?php 
echo $this->formElement($form->get('id'));
echo $this->formLabel($form->get('employeeNumber'));
echo $this->formElement($form->get('employeeNumber'));
echo $this->formElementErrors($form->get('employeeNumber')); 
echo $this->formLabel($form->get('Role01'));
echo $this->formElement($form->get('Role01'));
echo $this->formElementErrors($form->get('Role01'));
echo $this->formLabel($form->get('duration01'));
echo $this->formElement($form->get('duration01'));
echo $this->formElementErrors($form->get('duration01'));
echo $this->formLabel($form->get('lOI01'));
echo $this->formElement($form->get('lOI01'));
echo $this->formElementErrors($form->get('lOI01'));
echo $this->formLabel($form->get('content01'));
echo $this->formElement($form->get('content01'));
echo $this->formElementErrors($form->get('content01'));

//echo $this->formSubmit ( $form->get ( 'submit' ) );
?>
</div>
<div style="Float:left;width:320px;">	

<?php
echo $this->formLabel($form->get('Role02'));
echo $this->formElement($form->get('Role02'));
echo $this->formElementErrors($form->get('Role02'));
echo $this->formLabel($form->get('duration02'));
echo $this->formElement($form->get('duration02'));
echo $this->formElementErrors($form->get('duration02'));
echo $this->formLabel($form->get('lOI02'));
echo $this->formElement($form->get('lOI02'));
echo $this->formElementErrors($form->get('lOI02'));
echo $this->formLabel($form->get('content02'));
echo $this->formElement($form->get('content02'));
echo $this->formElementErrors($form->get('content02'));

?>  
</div> 
</fieldset>
<fieldset style="padding:5px;" >
     <legend>&nbsp;</legend>
<div style="float: left; width: 370px; margin: -10px 0 0 0;">
<?php 
echo $this->formLabel($form->get('Role03'));
echo $this->formElement($form->get('Role03'));
echo $this->formElementErrors($form->get('Role03'));
echo $this->formLabel($form->get('duration03'));
echo $this->formElement($form->get('duration03'));
echo $this->formElementErrors($form->get('duration03'));
echo $this->formLabel($form->get('lOI03'));
echo $this->formElement($form->get('lOI03'));
echo $this->formElementErrors($form->get('lOI03'));
echo $this->formLabel($form->get('content03'));
echo $this->formElement($form->get('content03'));
echo $this->formElementErrors($form->get('content03'));
//echo $this->formSubmit ( $form->get ( 'submit' ) );
?>
</div>
<div style="Float:left;width:320px;">	
<?php
echo $this->formLabel($form->get('Role04'));
echo $this->formElement($form->get('Role04'));
echo $this->formElementErrors($form->get('Role04'));
echo $this->formLabel($form->get('duration04'));
echo $this->formElement($form->get('duration04'));
echo $this->formElementErrors($form->get('duration04'));
echo $this->formLabel($form->get('lOI04'));
echo $this->formElement($form->get('lOI04'));
echo $this->formElementErrors($form->get('lOI04'));
echo $this->formLabel($form->get('content04'));
echo $this->formElement($form->get('content04'));
echo $this->formElementErrors($form->get('content04'));
?> 
</div>    	
</fieldset>
<fieldset style="padding:5px;" >
     <legend>&nbsp;</legend>
<div style="float: left; width: 370px; margin: -10px 0 0 0;">
<?php 
echo $this->formLabel($form->get('Role05'));
echo $this->formElement($form->get('Role05'));
echo $this->formElementErrors($form->get('Role05'));
echo $this->formLabel($form->get('duration05'));
echo $this->formElement($form->get('duration05'));
echo $this->formElementErrors($form->get('duration05'));
echo $this->formLabel($form->get('lOI05'));
echo $this->formElement($form->get('lOI05'));
echo $this->formElementErrors($form->get('lOI05'));
echo $this->formLabel($form->get('content05'));
echo $this->formElement($form->get('content05'));
echo $this->formElementErrors($form->get('content05'));
echo $this->formSubmit ( $form->get ( 'submit' ) );
?>
</div>
<div style="Float:left;width:320px;">	

</div>    	
</fieldset>
<?php
echo $this->form ()->closeTag ();
?>
</div>
</div>
</div>