<?php 
	$title = 'Update Attendance Group';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
	echo $this->formLabel($form->get('groupName'));
	echo $this->formElement($form->get('groupName'));
	echo $this->formElementErrors($form->get('groupName')); 
	echo $this->formSubmit($form->get('submit'));
	echo $this->form ()->closeTag ();
?>
