<h3>Edit Employee Bank Information</h3>
<?php
echo $this->form ()->openTag ( $form );
echo $this->formRow ( $form->get ( 'id' ) ) . "</br>";
echo $this->formRow ( $form->get ( 'emp_personal_info_id' ) ) . "</br>";
echo $this->formRow ( $form->get ( 'lkp_bank_id' ) ) . "</br>";
echo $this->formRow ( $form->get ( 'account_number' ) ) . "</br>";

?>
<hr></hr>
<?php
echo $this->formSubmit ( $form->get ( 'submit' ) ) . "</br>";
echo $this->form ()->closeTag ();
?>
</br>
</br>
<a href="<?php echo $this->url('employee'); ?>">Back</a>
