<h1>Employee Index</h1>

<a href="<?php echo $this->url('employee',array('action' => 'add')); ?>">Add
	Employee</a>
</br>

<hr></hr>

<h2>Personal Info</h2>
<a
	href="<?php echo $this->url('employee',array('action' => 'personalInfoIndex')); ?>">Personal
	Info Index</a>
</br>
<a
	href="<?php echo $this->url('employee',array('action' => 'pendingPersonalInfo')); ?>">Pending
	Personal Info</a>
</br>

<hr></hr>

<h2>Bank Info</h2>
<a
	href="<?php echo $this->url('employee',array('action' => 'bankInfoIndex')); ?>">Bank
	Info Index</a>
</br>
<a
	href="<?php echo $this->url('employee',array('action' => 'pendingBankInfo')); ?>">Pending
	Bank Info</a>
</br>

<hr></hr>

<h2>Employee Info</h2>
<a
	href="<?php echo $this->url('employee',array('action' => 'employeeInfoIndex')); ?>">Employee
	Info Index</a>
</br>
<a
	href="<?php echo $this->url('employee',array('action' => 'pendingEmployeeInfo')); ?>">Pending
	Employee Info</a>
</br>

<h2>Employee Location</h2>
<a
	href="<?php echo $this->url('location',array('action' => 'add')); ?>">Employee
	Location</a>
</br>

</br>
