<h1>Pending Employee Bank Info</h1>

<table class="table">
	<tr>
		<th>Personal Info Id</th>
		<th>Bank Id</th>
		<th>Account Number</th>
		<th>Action</th>
	</tr>
<?php
foreach ( $pending as $row ) :
	?>
    <tr>
		<td><?php echo $row->getEmpPersonalInfoId(); ?></td>
		<td><?php echo $row->getLkpBankId(); ?></td>
		<td><?php echo $row->getAccountNumber(); ?></td>
		<td><a
			href="<?php echo $this->url('employee',array('action' => 'approveBankInfo','id' => $row->getId())); ?>">Approve</a>
			<a
			href="<?php echo $this->url('employee',array('action' => 'rejectBankInfo','id' => $row->getId())); ?>">Reject</a>
		</td>
	</tr>
<?php
endforeach
;
?>
    
</table>
</br>
</br>
<a href="<?php echo $this->url('employee'); ?>">Back</a>
