<h1>Employee Personal Info - Index</h1>

<table class="table">
	<tr>
		<th>Personal Info Id</th>
		<th>Name</th>
		<th>Address</th>
		<th>Action</th>
	</tr>
<?php
foreach ( $info as $row ) :
	?>
    <tr>
		<td><?php echo $row->getEmpPersonalInfoId(); ?></td>
		<td><?php echo $row->getEmployeeName(); ?></td>
		<td><?php echo $row->getAddress(); ?></td>
		<td><a
			href="<?php echo $this->url('employee',array('action' => 'editPersonalInfo','id' => $row->getEmpPersonalInfoId())); ?>">Edit</a>
			<a
			href="<?php echo $this->url('employee',array('action' => 'deletePersonalInfo','id' => $row->getEmpPersonalInfoId())); ?>">Delete</a>
		</td>
	</tr>
<?php
endforeach
;
?>
    
</table>
</br>
</br>
<a href="<?php echo $this->url('employee'); ?>">Back</a>
