<?php
$title = 'Leave Entitlement admin';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('leave', array('action'=>'index'));?>">go
		back</a>
</p>

<
<table class="table">
	<tr>
		<th>Years Of Service</th>
		<th>Number Of Days</th>
		<th>company id</th>

		<th>&nbsp;</th>
	</tr>
    <?php
				
foreach ( $entitlement as $a ) :
					// var_dump($a);
					// Zend\Debug\Debug::dump($this);
					// <-- change here!					?>
        <tr>

		<td><?php echo $this->escapeHtml($a->getYearsOfService());?></td>
		<td><?php echo $this->escapeHtml($a->getNumberOfDays());?></td>
		<td><?php echo $this->escapeHtml($a->getCompanyId());?></td>

		<td><a
			href="<?php
					
echo $this->url ( 'entitlementadmin', array (
							'action' => 'approve',
							'id' => $a->getId () 
					) );
					?>">approve</a>
			<a
			href="<?php
					
echo $this->url ( 'entitlementadmin', array (
							'action' => 'reject',
							'id' => $a->getId () 
					) );
					?>">Reject</a>
		</td>
	</tr>
    <?php endforeach; ?>
</table>
<?php // add at the end of the file after the table
/*echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'LeaveEntitlement'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'entitlement'
    )
);*/
