<?php
$title = 'reject leave Entitlemnt';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<P>Are you sure you want to reject</P>
<?php
$url = $this->url ( 'entitlementadmin', array (
		'action' => 'reject',
		'id' => $id 
) );
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
		<!--  < <input type="hidden" name="id" value="//<?//php echo (int) $project->getProjectId; ?>" />-->
		<input type="submit" name="reject" value="Yes" /> <input type="submit"
			name="reject" value="No" />
	</div>
</form>