<?php 
	$title = 'Approve New Employee List'; 
	$this->headTitle($title); 
	echo "<h3>".$title."</h3>";   
?>  
<br/> 
<br/> 

<?php 
	echo $this->form()->openTag($form);  
	echo $this->formLabel($form->get('effectiveDate')); 
    echo $this->formElement($form->get('effectiveDate')); 
    echo $this->formElementErrors($form->get('effectiveDate')); 
	echo $this->formSubmit($form->get('submit'));  
	echo $this->form()->closeTag();  
?>  
<br/><br/>  
<div id="dialog">Are you sure remove this record?</div>
<div id="tableContainer"></div> 
<script>$("#tableContainer").zfTable('/newemployee/ajaxlistnew');</script>  
<br/><br/> 