<?php 
	$title = 'Terminated Employee Report';
	$this->headTitle($title);
	//echo "<h3>".$title."</h3>";
?>
<div >
<?php 

$form = $this->form;

$form->setAttribute('action', $this->url(
	'newemployee', array(
		'action'     => 'viewterminatedreport',
		'controller' => 'newemployee'
	)
)); 
$form->setAttribute('target','_blank');
$form->prepare();
    
?>
</div> 
<style type="text/css">
    label  { font-weight:normal; }
    li { color:red; }
</style>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Terminated Employee Report</a></li>
		<!-- <li><a href="#tabs-2">Search Report</a></li>-->
	</ul>
<div id="tabs-1"> 
<?php echo $this->form()->openTag($form); ?>
<div>
    <fieldset style="padding:5px;" >
        <legend>Employee Info</legend>
            <div style="float:left;width:320px;margin:-10px 0 0 0;">
            <?php 
                echo $this->form()->openTag($form);  
			    echo $this->formLabel($form->get('month'));
			    echo $this->formElement($form->get('month'));
			    echo $this->formElementErrors($form->get('month'));
			    echo $this->formLabel($form->get('year'));
			    echo $this->formElement($form->get('year'));
			    echo $this->formElementErrors($form->get('year')); 
			    echo $this->formSubmit($form->get('submit'));
			    echo $this->form()->closeTag();
            ?>
            </div>				
            		
    </fieldset>
    
</div>
<?php echo $this->form()->closeTag ();?>
</div>
</div>
