<?php 
$title = 'Report Employee';
$this->headTitle($title); 
?>
<style>
table, td, th { border: 1px solid #ccc;border-collapse: collapse; }
thead { background-color: #ccc;color:#000;font-weight:bold; }
th { background-color: green;color: white; }
td { padding: 5px; }
td { height: 40px;vertical-align: bottom;border-collapse: collapse; }
</style>
<div id="tabs">
<?php 
//\Zend\Debug\Debug::dump($this->report);
//foreach ($this->report as $r) {
	//\Zend\Debug\Debug::dump($r);
//}
echo $this->genReportHelper($this->nameList,$this->report);  
?> 
</div>  