<?php 
	$title = 'Add Overtime'; 
	$this->headTitle($title); 
	//echo "<h3>".$title."</h3>"; 
?>
<div >
<?php 

$form = $this->form; 

$form->setAttribute('target','_self');  //_blank
$form->prepare(); 
    
?>
</div> 
<style type="text/css">
    label  { font-weight:normal; }
    li { color:red; }
</style>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Upload Employee Overtime for current month</a></li>
		<!-- <li><a href="#tabs-2">Search Report</a></li>-->
	</ul> 
<div id="tabs-1"> 
<?php $form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>
     <?php //echo $this->formFileSessionProgress(); ?>
    <div class="form-element">
        <?php $fileElement = $form->get('otFile'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>
    <br/><br/>  
    <button>Submit</button>

<?php echo $this->form()->closeTag(); ?>
<?php /* echo $this->form()->openTag($form); ?>
<div>
    <fieldset style="padding:5px;" >
        <legend>Add OverTime Hours for Employee </legend>
            <div style="float:left;width:720px;margin:-10px 0 0 0;">
            <?php 
//                echo $this->formLabel($form->get('overtimeMstId'));
//                echo $this->formElement($form->get('overtimeMstId'));
//                echo $this->formElementErrors($form->get('overtimeMstId'));
                
                 echo $this->formLabel($form->get('empId'));
                echo $this->formElement($form->get('empId'));
                echo $this->formElementErrors($form->get('empId'));
                
                echo $this->formLabel($form->get('employeeNoNOHours'));
                echo $this->formElement($form->get('employeeNoNOHours'));
                echo $this->formElementErrors($form->get('employeeNoNOHours'));
                
                echo $this->formLabel($form->get('employeeNoHOHours'));
                echo $this->formElement($form->get('employeeNoHOHours'));
                echo $this->formElementErrors($form->get('employeeNoHOHours'));
                
//                
//                echo $this->formLabel($form->get('overtimeMstId'));
//                echo $this->formElement($form->get('overtimeMstId'));
//                echo $this->formElementErrors($form->get('overtimeMstId'));
                
//                 echo $this->formLabel($form->get('isClosed'));
//                echo $this->formElement($form->get('isClosed'));
//                echo $this->formElementErrors($form->get('isClosed'));

				echo $this->formSubmit($form->get('submit'));
				?> 
				 </div>			
            	</div>	
    </fieldset>
    
</div>
<?php echo $this->form()->closeTag(); */ ?>
</div>
<!--  
<div id="dialog">Are you sure remove this record?</div> 
<div id="overtimeContainer"></div>
<script>$("#overtimeContainer").zfTable('/overtime/ajaxlist');</script> 
--> 
<br/><br/> 
</div> 