<?php 
	$title = 'Update Employee Allowance';
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
	echo $this->formLabel($form->get('employeeId')); 
	echo $this->formElement($form->get('employeeId')); 
	echo $this->formElementErrors($form->get('employeeId')); 
	echo $this->formLabel($form->get('amount')); 
	echo $this->formElement($form->get('amount')); 
	echo $this->formElementErrors($form->get('amount')); 
	echo $this->formLabel($form->get('effectiveDate'));
	echo $this->formElement($form->get('effectiveDate'));
	echo $this->formElementErrors($form->get('effectiveDate'));
	echo $this->formLabel($form->get('allowanceNameText'));
	echo $this->formElement($form->get('allowanceNameText'));
	echo $this->formElementErrors($form->get('allowanceNameText'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form ()->closeTag ();
	
?>