<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<p align="center"><strong>COMPENSATION  &amp; BENEFITS</strong><br clear="all" />
</p>
<div align="center"></div>
<p><b>1. POLICY STATEMENT:</b></p>
<p><br />
  It is the company's policy to pay to an employee a salary that is both  equitable and competitive.</p>
<p><br />
  <strong>2<u>. GENERAL</u></strong></p>
<ul>
  <li>The overall goal of the Compensation  and Benefits program at PMSL is to attract, retain and motivate a  high-performing workforce.</li>
  <li>HR &amp; Administration Department conducts  annual market survey to ensure that the total compensation program remains  competitive.</li>
  <li>The salary of the employee shall be  determined by the Company and shall be within the company&rsquo;s salary structure.  Employee shall be informed of the salary grade applicable to him/her at the  time of confirmation in service and whenever he/she is promoted.</li>
</ul>
<p><strong>3.<u> SALARY DEFINTIONS:</u></strong></p>
<ul>
  <li>Basic Salary shall mean the Initial Salary  and Cost of Living Allowance (COLA). </li>
  <li>The monthly payment to employee consist  of basic salary in addition to other allowances, which is sum payable to  employee for service with the company and will be paid at the end of the month.</li>
</ul>
<p><strong>4<u>. SALARY OF NEW HIRED EMPLOYEE: </u></strong></p>
<ul>
  <li> The salary at the point of entry shall be  determined by the following factors: </li>
  <li> Salary  grade to be offered to the candidate.</li>
  <li>Relevant working experience (in terms  of years) of the candidate. </li>
  <li>Candidate&rsquo;s present gross income  wherever relevant.</li>
  <li>Level of salary expected by the  candidate.</li>
  <li>Salary levels of existing staff of  similar working experience and level of responsibility.</li>
  <li>Educational and competency  qualifications.</li>
  <li>Market salary level of the job.</li>
  <li>As a general guide :-</li>
  <li>A degree holder with less than two  years &lsquo; relevant working experience shall be   offered appointment on salary grade 20 and paid basic salary in accordance  with the salary structure.</li>
  <li>The salary offered to a prospective  employee may be lower than that of existing staff of similar working experience  and level of responsibility in the company. Exceptions to this rule will be  made when the position to be filled requires a critical skill which is scarce  in the labor market.</li>
</ul>
<div align="center"></div>
<p><strong> 5.<u> SALARY OF AN EMPLOYEE ON PROMOTION</u></strong> </p>
<p><br />
  An employee on the promotion shall be  paid an increment to be determined by the company i.e. 10 % of the mid-point of  the next higher grade or top of quartile 1 of the next higher grade whichever  is higher.</p>
<p><br />
  <strong>6. <u>SALARY ADJUSTMENT</u></strong></p>
<p><br />
  <strong>      </strong>Upward salary adjustments may be  granted to an employee to correct pay anomalies on the following basis:-  </p>
<ul>
  <ul>
    <li>Salary  at the point – of- entry offered to him/her is much lower than the normal level  of the   salary paid to employee of  similar experience and qualification.</li>
  </ul>
</ul>
<p>6 .2To recognize his/her level of  skills, education and competency.</p>
<p><br />
  <strong><u>7.  OVER PAYMENT OF SALARY AND ALLOWANCES </u></strong> </p>
<p><br />
  Overpayment of salary and allowances by  mistake must be recovered from the employee as soon as possible.  </p>
<p><br />
  <strong><u>8. SALARY  ADVANCE</u></strong></p>
<p><br />
  The Company may consider paying an  advance of salary upon request of the employee on the following grounds:-</p>
<ul>
  <li>To make arrangement / preparation for  long term overseas assignment/training.</li>
  <li>For marriage.</li>
  <li>For purpose of performing the Haj.</li>
  <li>For some other justifiable reasons.</li>
  <li> The  maximum salary advance is one month salary.</li>
  <li>The salary advance must be deducted  from employee salary in two months.</li>
</ul>
<div align="center"></div>
<p>1.  <strong><u>POLICY </u>                                                                                                                                         <u></u></strong></p>
<p>It  is the company policy to grant salary increment based on the employee&rsquo;s performance  rating and his/her current salary quartile.  </p>
<p><br />
  2.    <strong><u>ANNUAL  BASE SALARY NCREMENT</u></strong><br />
  <strong><u>Quantum: </u></strong></p>
<ul>
  <ul>
    <li>Performance Rating:<strong></strong></li>
  </ul>
</ul>
<p>Increment  shall be granted based on three (3) performances rating namely:-<strong></strong></p>
<ul>
  <li>Outstanding </li>
  <li>Exceeds  Requirements </li>
  <li>Meets  Requirements.</li>
</ul>
<p>             Or any other rating scales  which may be approved by the company.<br />
  2.2 Quartile of current salary.</p>
<p><br />
  <strong><u>Eligibility  Criteria: </u></strong></p>
<ul>
  <li>Employee must have been rated at least  the performance cut off rate, which is annually determined by the company for  the performance cycle.<strong><u></u></strong></li>
  <li>Employee must have been confirmed in  the permanent service by end of 31 December of year eligible for performance  assessment. <strong><u></u></strong></li>
  <li>Employee with less than 12 months of  service as of 31 December of year eligible for performance assessment will have  an increment affected at his / her anniversary date of joining the company.<strong></strong></li>
</ul>
<p><strong><u>       </u></strong><br />
  <strong><u>3.  ANNIVERSERY AND  ANNUAL INCREMENT  </u></strong></p>
<p><strong>   </strong>         The company will grant an employee the first  increment on the anniversary date of his / her appointment provided that the  employee&rsquo;s work performance during the relevant review period has been  satisfactory.<br />
  The  anniversary increment quantum is based on the prevailing annual increment rates  for the year, subsequent increments will be on the first of January of second  year.</p>
<p><br />
  <strong>   4<u>. INCREMENT FOR EMPLOYEE ON LONG TERM DEVELOPMENT  PROGRAM:</u></strong> </p>
<p><br />
  An employee will be granted an increment based  on his/ her performance and training appraisal.</p>
<p><br />
  <strong>5. <u> EMPLOYEE REACHING THE  MAXIMUM OF SCALE</u></strong></p>
<p><br />
  An employee who has reached the maximum of his/ her salary  grade range will not be paid the increment. However he /she will be paid  performance allowance which is the lump sum of the increment based on his/her  performance rating.<strong>  </strong></p>
<p><strong>                                                        </strong><br />
  <strong><u>6. INCREMENT FOR EMPLOYEE ON PROLONGED ILLNESS.</u></strong></p>
<p><br />
  An employee on  prolonged illness will not be paid increment.   </p>
<div align="center"></div>
<p><strong>1.  <u>POLICY </u> </strong></p>
<p><strong>                                                                                                                                       <u></u></strong><br />
  It  is the company&rsquo;s policy to pay bonus based on overall company&rsquo;s performance  results to confirmed employee as an appreciation of his/her service to the  Company during financial year. </p>
<p><br />
  <strong><u>Definition:</u></strong></p>
<p><br />
  Bonus is payment by company to <u>confirmed</u> employees in recognition of achieving targeted performance results during  financial year. Bonus pay is also used to improve employees&rsquo; morale, motivation  and productivity.   <br />
  At the discretion of the Board of  Directors, PMSL might consider paying its employees annual bonus. This is based  on overall company&rsquo;s performance results during the financial year as well as  affordability. The quantum of the payment depends on employee annual  performance result rating.</p>
<p><br />
  2.  <strong><u>Eligibility  Criteria:</u></strong></p>
<ul>
  <li>  An employee who is confirmed by end of 31  December and eligible to PMS cycle of the year is entitled to full or a  proportional share of the bonus depending on the period of service with the  Company in the financial year.</li>
  <li>  An employee who is attending learning&amp;  development program is also eligible for bonus on condition that he / she is  confirmed in his/ her position on or before 31 December.</li>
  <li> An employee who should receive his/her  anniversary increment or salary adjustment on or before 31 December but has not  received it on the bonus declaration date, shall be paid bonus based on his /  her present basic salary.  Accordingly,  the bonus shall be adjusted when his/ her anniversary increment or salary  adjustment is due.</li>
  <li>  An employee whose employment with the Company  is ceased by way of death or is medically boarded out shall be eligible to  bonus payment proportions to his completed days of the services.</li>
  <li>An employee who retires from his  employment with the Company on or after reaching the age of retirement ( 60 )  in respect of the financial year in which he/she retires , shall be paid bonus  in proportion to that part of the year for which he actually been employed.</li>
</ul>
<p><strong> </strong><br />
</p>
<div align="center"></div>
<p><strong>The  following are employees who are not eligible for bonus:-</strong></p>
<p><br />
  The  resigned employee whose resignation date is effective before 31st of  December is not eligible for bonus.<strong></strong><br />
  <strong>         </strong>The bonus  payment for an employee undergoing disciplinary proceeding will depend on the  decision of the management.  </p>
<p><br />
  <strong><u>BASIS  FOR CALCULATING BONUS PAYMENT</u></strong><strong>:</strong></p>
<p><br />
  Payment  of the bonus for an employee who has less than one year service during the   bonus   year shall be determined as below :-<br />
  <br />
  <u>Basic Salary    x       <strong>  </strong>No of days served      x       Bonus Quantum<strong></strong></u><br />
  365</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p> </p>
</body>
</html>
