<?php 
    $title = 'Final Entitlement';
    $this->headTitle($title);
?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<p>&nbsp;</p>
<p><strong>Effective  Date:  April.2014</strong></p>
<p>&nbsp;</p>
<table border="1" cellspacing="0" cellpadding="0" >
  <tr>
      <td width="216" rowspan="4" valign="top"><p align="center"><img src="/img/oilEnergyLogo.jpg" alt="Oil Energy Logo" /></p></td>
      <td width="401" rowspan="4" valign="top"><p align="center"><strong>&nbsp;</strong></p>
        <p><strong>After    Services Benefit</strong><br />
          <strong>                            (A) </strong><strong> </strong></p></td>
      <td width="195" valign="top"><p>Index No.:<br />
        OCEL -HRS -501 to 506</p></td>
  </tr>
    <tr>
      <td width="195" valign="top"><p>Issue       : 1</p></td>
    </tr>
    <tr>
      <td width="195" valign="top"><p>Rev. No  :New</p></td>
    </tr>
    <tr>
      <td width="195" valign="top"><p>Page <strong>2</strong><strong> </strong> of 2</p></td>
    </tr>
</table>

<p>&nbsp;</p>
<p><strong><u>POLICY </u></strong><br />
  OECL is  committed to pay its contribution of Social Insurance 17% and profit   and fund 20%.<a name="_Toc343764357" id="_Toc343764357"></a><a name="_Toc342005479" id="_Toc342005479"></a><a name="_Toc341973597" id="_Toc341973597"></a><a name="_Toc147455775" id="_Toc147455775"></a><a name="_Toc117151754" id="_Toc117151754"><strong> </strong></a> In addition to that OCEL committed to pay After  Services Benefit.<br />
  <strong>  <u>ELIGLIBLITY</u></strong><br />
  To all employee.<br />
  <strong>  <u>ENTITLMENT</u></strong><br />
  1/  If employee   has completed 25 years and more, he /she shall be entitled to two and  half month&rsquo;s not exceeding total amount of   seventy five months  basic salary  .<br />
  2/ If employee  has completed One to Ten years in services he /she entitled to one month basic  salary.<br />
  3/  / If employee   has completed Eleven  to Twenty  years in services he /she    entitled to  two  months basic salary for each year.<br />
  4/ If employee  has completed Twenty one to Twenty four years in services       he /she entitled to two and half months  basic salary for each year.</p>
<p><strong><u> General Term &amp;  condition </u></strong><br />
  1/ the gratuities are calculated on the  basis of the last monthly basic salary.<br />
  2/   The Company shall pay all  traveling cost for employ and their direct family <br />
  3/  The Company shall pay to the retired employee  &amp; his /her family (husband/ wife &amp;kids), cost of traveling , household  goods and stuff. <br />
4/ in case of death of employee  during service the  company shall pay to  his/her family 24 month last basic salary or the amount of calculation for  after services benefit as he/she number of services year which is higher.</p>
<p>&nbsp;</p>
<p>  </p>
<p>&nbsp;</p>
</body>
</html>
