<style>
<!--
p {
    font-size:14px;
}
-->
</style>

<?php 
    $title = 'Paysheet';  
    $this->headTitle($title);  
?>  
<h3>Policy And Manual</h3>
<p><b>Process Before Paysheet</b></p>
<p><b>Compulsory Process to be done and Closed</b></p>
<p>1.Overtime <br />
  2.Telephone Deduction<br />
</p>
<p><b>Process To Be closed if Prepared</b><br /><br /> 
  1.Advance Salary<br />
  2.Personal Loan<br />
  3.Other Deduction/Over Payment<br />
  4.Advance Housing<br />
  5.Staff Movement<br />
  6.Promotion</p>
  
  
  
<p>&nbsp;</p>
<p><strong><u> SALARY DEFINTIONS:</u></strong></p>
<ul>
  <li>Basic Salary shall mean the Initial Salary  and Cost of Living Allowance (COLA). </li>
  <li>The monthly payment to employee consist  of basic salary in   addition to other allowances, which is sum payable to  employee for   service with the company and will be paid at the end of the month.</li>
</ul>
<p><strong><u>SALARY OF NEW HIRED EMPLOYEE: </u></strong></p>
<ul>
  <li> The salary at the point of entry shall be  determined by the following factors: </li>
  <li> Salary  grade to be offered to the candidate.</li>
  <li>Relevant working experience (in terms  of years) of the candidate. </li>
  <li>Candidate&rsquo;s present gross income  wherever relevant.</li>
  <li>Level of salary expected by the  candidate.</li>
  <li>Salary levels of existing staff of  similar working experience and level of responsibility.</li>
  <li>Educational and competency  qualifications.</li>
  <li>Market salary level of the job.</li>
  <li>As a general guide :-</li>
  <li>A degree holder with less than two  years &lsquo; relevant working   experience shall be   offered appointment on salary grade 20 and paid   basic salary in accordance  with the salary structure.</li>
  <li>The salary offered to a prospective  employee may be lower than   that of existing staff of similar working experience  and level of   responsibility in the company. Exceptions to this rule will be  made   when the position to be filled requires a critical skill which is scarce    in the labor market.</li>
</ul>
<div align="center"></div>
<p><br />
<strong><u>  OVER PAYMENT OF SALARY AND ALLOWANCES </u></strong></p>
<p><br />
  Overpayment of salary and allowances by  mistake must be recovered from the employee as soon as possible.  </p>
<p><br />
  <strong><u>SALARY  ADVANCE</u></strong></p>
<p><br />
  The Company may consider paying an  advance of salary upon request of the employee on the following grounds:-</p>
<ul>
  <li>To make arrangement / preparation for  long term overseas assignment/training.</li>
  <li>For marriage.</li>
  <li>For purpose of performing the Haj.</li>
  <li>For some other justifiable reasons.</li>
  <li> The  maximum salary advance is one month salary.</li>
  <li>The salary advance must be deducted  from employee salary in two months.</li>
</ul>
<div align="center"></div>
<p>&nbsp;</p>