<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Index
 *
 * @author AlkhatimVip
 */
if (isset ( $approve )) {
	$title = 'Approve Level';
	$this->headTitle ( $title );
	$url = $this->url ( 'level', array (
			'action' => 'approve',
			'id' => $approve->getPositionLevelId () 
	) );
	echo "<form action='$url' method='post'>";
	echo "<h3>Are you sure you want to approve this level?</h3>";
	echo "<label>ID</label>" . $approve->getPositionLevelId () . "<br/>";
	echo "<label>Sequence</label>" . $approve->getLevelSequence () . "<br/>";
	echo "<label>Name</label>" . $approve->getLevelName () . "<br/>";
	// echo "<label>added by </label> ".$approve->getAddedUser()." <label> on </label> ".$approve->getAddedDate()."<br/>";
	echo "<div>
            <input type='submit' name='approved' value='Yes' />
            <input type='submit' name='approved' value='No' />
          </div>";
} else {
}