<?php
/**
 * Description of Index
 *
 * @author AlkhatimVip
 */
if (isset ( $approve )) {
	$title = 'Reject Level';
	$this->headTitle ( $title );
	$url = $this->url ( 'level', array (
			'action' => 'reject',
			'id' => $approve->getPositionLevelId () 
	) );
	echo "<form action='$url' method='post'>";
	echo "<h3>Are you sure you want to reject/cancel this level?</h3>";
	echo "<label>ID</label>" . $approve->getPositionLevelId () . "<br/>";
	echo "<label>Sequence</label>" . $approve->getLevelSequence () . "<br/>";
	echo "<label>Name</label>" . $approve->getLevelName () . "<br/>";
	// echo "<label>added by </label> ".$approve->getAddedUser()." <label> on </label> ".$approve->getAddedDate()."<br/>";
	echo "<div>
            <input type='submit' name='cancelled' value='Yes' />
            <input type='submit' name='cancelled' value='No' />
          </div>
    </form>";
} else {
}