<?php 
	$title = 'Add Location Group';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formLabel($form->get('locationId'));
	echo $this->formElement($form->get('locationId'));
	echo $this->formElementErrors($form->get('locationId'));
	echo $this->formLabel($form->get('attendanceGroupId'));
	echo $this->formElement($form->get('attendanceGroupId'));
	echo $this->formElementErrors($form->get('attendanceGroupId'));
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();  
?>