<?php 
	$title = 'Add Overtime Meals'; 
	$this->headTitle($title); 
	//echo "<h3>".$title."</h3>"; 
?>
<div >
<?php 

$form = $this->form; 

$form->setAttribute('target','_self');  //_blank
$form->prepare(); 
    
?>
</div> 
<style type="text/css">
    label  { font-weight:normal; }
    li { color:red; }
</style>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Add OverTime Meals for Employee</a></li>
		<!-- <li><a href="#tabs-2">Search Report</a></li>-->
	</ul> 
<div id="tabs-1"> 
<?php echo $this->form()->openTag($form); ?>
<div>
    <fieldset style="padding:5px;" >
        <legend>Add Number Of Meals </legend>
            <div style="float:left;width:720px;margin:-10px 0 0 0;">
            <?php 
                
                echo $this->formLabel($form->get('empId'));
                echo $this->formElement($form->get('empId'));
                echo $this->formElementErrors($form->get('empId'));
                
                echo $this->formLabel($form->get('amount'));
                echo $this->formElement($form->get('amount'));
                echo $this->formElementErrors($form->get('amount'));
                
                echo $this->formLabel($form->get('employeeNoMeals'));
                echo $this->formElement($form->get('employeeNoMeals'));
                echo $this->formElementErrors($form->get('employeeNoMeals'));
                
               	echo $this->formSubmit($form->get('submit'));
				?>
				 </div>			
            	</div>	
    </fieldset>

</div>
<?php echo $this->form()->closeTag ();?>
</div>
<div id="dialog">Are you sure remove this record?</div> 
<div id="overtimemealContainer"></div>
<script>$("#overtimemealContainer").zfTable('/otmeal/ajaxlist');</script> 
<!--<script>$("#overtimeContainer").zfTable('/overtime/ajaxlist');</script>  ================Overtime Ajax-->
<!--<script>$("#newEmployeePositionContainer").zfTable('/overtimemst/ajaxlist');</script> -->
<br/><br/>
<!-- 
    <div id="tabs-2">
        <p>search form</p>
    </div>
--> 
</div> 