<?php 
	$title = 'Apply OT Meal';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form); 
	echo $this->formSubmit($form->get('submit'));  //apply overtime button
	echo $this->form()->closeTag();  
?>  
<br/>
<div id="dialog">Are you sure remove this record?</div> 
<div id="overtimemealContainer"></div>
<script>$("#overtimemealContainer").zfTable('/otmeal/ajaxlist');</script> 
<br/>