<?php
$title = 'Main Positions';
$this->headTitle ( $title );
?>
<table class="table">
	<thead>
		<th>code</th>
		<th>Name</th>
		<th>Level</th>
		<th>section</th>
		<th>Status</th>
		<th>&nbsp;</th>
	</thead>
    <?php foreach ($positions as $position) : ?>
        <tr>
		<td><?php echo $this->escapeHtml($position->getPositionCode());?></td>
		<td><?php echo $this->escapeHtml($position->getPositionName());?></td>
		<td><?php echo $this->escapeHtml($levels[$position->getPositionLevelId()]);?></td>
		<td><?php echo $this->escapeHtml($sections[$position->getSectionId()]);?></td>
		<td><?php echo $this->escapeHtml($position->getPositionStatus());?></td>
		<td><a
			href="<?php echo $this->url('position',array('action' => 'edit','id'=> $position->getPositionId()));?>">edit</a></td>
	</tr> 
    <?php endforeach; ?>
</table>