<script> 
    $(function() { 
    	$("#employeeId").combobox("disable"); 
    });  
</script> 
<?php 
	$title = 'Delete Suspend';
	$this->headTitle($title);
	echo "<h3>".$title."</h3>";
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formElement($form->get('id'));
	echo $this->formLabel($form->get('employeeId'));
	echo $this->formElement($form->get('employeeId'));
	echo $this->formElementErrors($form->get('employeeId'));
	echo $this->formLabel($form->get('suspendFrom'));
	echo $this->formElement($form->get('suspendFrom'));
	echo $this->formElementErrors($form->get('suspendFrom'));
	echo $this->formLabel($form->get('suspendTo'));
	echo $this->formElement($form->get('suspendTo'));
	echo $this->formElementErrors($form->get('suspendTo'));
	echo $this->formLabel($form->get('reason'));
	echo $this->formElement($form->get('reason'));
	echo $this->formElementErrors($form->get('reason'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form ()->closeTag ();
?>
