<div>
  <div>
    <h2>LBVF Instruction</h2>
    <p><strong>Note : </strong></p>
    <p><strong>Deadline for Nomination &amp; Endorsement </strong>:</p>
    <p><strong>Deadline for Assessment </strong>: </p>
    <p>Nomination/Endorsement is not active at the moment</p>
    <p>Assessment is not active at the moment</p>
    <h3>Steps</h3>
    <ol>
      <li>Fill the People Management/Staff Involvement details(go to <strong><a href="http://lbvf/assesseedetails/">People Management/Staff Involvement</a></strong> link)</li>
      <li>Fill Nomination form(go to <strong><a href="http://lbvf/nominationform/">Nomination form</a></strong> Link)</li>
      <li>Endorse nominated form &quot;if supervisor&quot; (go to <strong><a href="http://lbvf/endorsement">Endorsement</a></strong>) Link</li>
      <li>Assessor have to assess nominee( go to <strong> <a href="http://lbvf/assessnominee">Assess Nominee</a></strong>) Link</li>
    </ol>
    <p><strong>Note :</strong>Please contact HR Department for further inquiries</p>
  </div>
</div> 